config/routes.rb
Sample::Application.routes.draw do
  devise_for :users

  get "login/index"

  root :to => 'login#index'
  match "chats", :controller => "chats", :action => "index"
  match "chat/create", :controller => "chats", :action => "create", :via => :post
  match "chats/index", :as => :user_root # ログイン後の遷移パス
  
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  attr_accessible :comment, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
 
  before_filter :authenticate_user!, :only => :index

  def index
  end

  def create
    Pusher["channel"].trigger("event", params[:text]+"<br />")
    render :text => "success"
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    # ログイン画面に遷移
    redirect_to :user_session
    return
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/chats/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<script type="text/javascript">
  $(function(){
    var pusher  = new Pusher("<%= '6f51c830bd0175d960c7' %>");
    var channel = pusher.subscribe("channel");
    channel.bind("event", function(html) {
      $("ul").prepend(html);
    });
  });
  $(document).ready(function(){
    $("#post").click(function(){
      $.ajax({
        type: "POST",
        url: "/chat/create",
        data: "text="+$('#text').val(),
        success: function() {},
      });
    });
  })
</script>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% end %><br/>
<input type="text" id="text" />
<input type="button" id="post">送信</input>

<ul>
<li></li>
</ul>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chat.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @chat.comment %>
</p>


<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  <%= javascript_include_tag "http://js.pusherapp.com/1.8/pusher.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="contents">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</div>

</body>
</html>

app/views/login/index.html.erb
<h1>Login#index</h1>
<p>Find me in app/views/login/index.html.erb</p>